openapi: 3.0.1
info:
  title: FRED API for GPT
  description: Get economic data from the FRED database using an API key.
  version: "1.0.0"
servers:
  - url: https://api.stlouisfed.org
paths:
  /fred/series/observations:
    get:
      summary: Get time series observations from FRED
      operationId: getFredObservations
      parameters:
        - in: query
          name: series_id
          required: true
          schema:
            type: string
          description: The ID of the FRED time series (e.g., CPIAUCSL)
        - in: query
          name: api_key
          required: true
          schema:
            type: string
          description: Your FRED API key
        - in: query
          name: file_type
          schema:
            type: string
            default: json
        - in: query
          name: observation_start
          schema:
            type: string
            format: date
            example: 2023-01-01
        - in: query
          name: observation_end
          schema:
            type: string
            format: date
            example: 2024-12-31
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
